### ISSUE TITLE
取时间没有返回后，会报异常退出

### ISSUE THREAD

**Issue by shensongjie** [guyongzx/SamsClub_buy#6]
当前获得的配送时间区域: 2022-05-12 09:00:00 至 2022-05-12 21:00:00
order [Error]: HTTPSConnectionPool(host='api-sams.walmartmobile.cn', port=443): Max retries exceeded with url: /api/v1/sams/trade/settlement/commitPay (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000021B75FCBA30>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
Exception in thread 16523172000001652360400000:1:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:/SamsClub_buy-master0504/normal_buy/order.py", line 112, in runOrder
    print("当前下单线程时间段-" + startStyleTime + " 至 " + endStyleTime + " 返回信息:" + res)
TypeError: can only concatenate str (not "NoneType") to str

**Comment by guyongzx** [comment]
fixed
